server:
  port:8085

spring:
  application:
    name: matching-service

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: 9092
    consumer:
      group-id: matching-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ridehailing.matchingservice.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ridehailing.matchingservice: INFO